logging:
  level:
      com.cuiyun.ddc: DEBUG
spring:
  application:
      name: ddc-rest
  datasource:
      name: test
      url: jdbc:mysql://${MYSQL_HOST:rm-uf6p6lsw9at9z1xkexo.mysql.rds.aliyuncs.com}:${MYSQL_PORT:3306}/kfcoding_research?useUnicode=true&characterEncoding=UTF8
      username: root
      password: 123qwe!@#
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis-plus:
  mapper-locations: classpath*:com/cuiyun/ddc/rest/dao/mapping/*.xml
  typeAliasesPackage: com.cuiyun.ddc.rest.model
#  typeEnumsPackage: com.cuiyun.kfcoding.basic.enums
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-repository: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

server:
    port: 9000

# 配置swagger
swagger:
    enabled: true
#    base-package: com.cuiyun.kfcdoing.basic.*
    title: ddc-rest
    version: 1.0.0.SNAPSHOT
    description: 基础模块服务
    contact:
        name: cuiyun

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

auth:
  user:
    token-header: Authorization